//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industry
{
    using System;
    using System.Collections.Generic;
    
    public partial class package
    {
        public int id___package { get; set; }
        public string Starting_point_of_the_package { get; set; }
        public Nullable<int> Final_destination_of_package { get; set; }
        public Nullable<double> Weight_parcel { get; set; }
        public Nullable<double> Volume_package { get; set; }
        public Nullable<double> Width { get; set; }
        public Nullable<double> Height { get; set; }
        public Nullable<double> Length { get; set; }
        public Nullable<bool> Status_cargo { get; set; }
        public Nullable<int> Cost { get; set; }
        public Nullable<int> Weight_category { get; set; }
        public string Login { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Tariff Tariff { get; set; }
    }
}
