//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Templates
    {
        public int id_pattern { get; set; }
        public string Loign { get; set; }
        public string Starting_point_of_the_package { get; set; }
        public Nullable<int> Final_destination_of_package { get; set; }
        public Nullable<double> Weight_parcel { get; set; }
        public Nullable<double> Volume_Package { get; set; }
        public Nullable<double> Dimensions_Package { get; set; }
    
        public virtual Clients Clients { get; set; }
    }
}
