//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Industry
{
    using System;
    using System.Collections.Generic;
    
    public partial class Weight_category
    {
        public int Id_Categories { get; set; }
        public Nullable<double> from { get; set; }
        public Nullable<double> before { get; set; }
        public string Weight_category1 { get; set; }
        public Nullable<int> Cost { get; set; }
    }
}
